language: ruby

rvm:
  - 2.0.0
bundler_args: --without development production

# This essentially defines a build pipeline: we first run the full set of locally runnable tests (unit + functional)
# For master pushes, we then deploy to comparably-test and push on to the staging branch.
# Travis then builds the staging branch, which runs integration tests against the newly-live staging deployment
# Once these pass, Travis deploys the code to live, and pushes to the prod branch (mostly just for reference)

# These also a special case for pull requests: these never push or deploy, and run the whole local test suite only

script:
  - if [[ "$TRAVIS_BRANCH" != "staging" ]]; then rake local_test; fi
  - if [[ "$TRAVIS_BRANCH" == "staging" ]]; then rake staging_integration; fi

deploy:
  provider: heroku
  app:
    master: unnamedapp-test
    staging: unnamedapp
  api_key:
    # secure: TODO uncomment and add your encrypted heroku deploy key here

after_success:
  # TODO update git urls below
  # Various pushes to branches. Need to pipe to null to not expose OAuth token
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      git push https://${GH_OAUTH_TOKEN}@github.com/you/unnamedapp master:staging > /dev/null 2>&1;
    fi
  - if [[ "$TRAVIS_BRANCH" == "staging" ]]; then
      git push https://${GH_OAUTH_TOKEN}@github.com/you/unnamedapp staging:prod > /dev/null 2>&1;
    fi

branches:
  except:
    - prod # No point in building prod, since we've just pushed from successful staging & master builds already

env:
  global:
    # secure: TODO uncomment and add your encrypted GH_OAUTH_TOKEN here